// historical-data-analysis/frontend/src/components/charts/line-chart.component.jsx
import React from "react";
import './line-chart.styles.css';

import { Line } from 'react-chartjs-2'
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
  } from 'chart.js';

ChartJS.register(
      CategoryScale,
      LinearScale,
      PointElement,
      LineElement,
      Title,
      Tooltip,
      Legend
);

const LineCharts = ({ indicatorName, labels, data, indicatorName2, className}) => {


    const options = {
        maintainAspectRatio: true,
        responsive: true,
        plugins: {
          title: {
              display: true,
              text: indicatorName, 
          },
      },
  };

    const chartData = {
        labels,
        datasets: [
          {
            label: indicatorName2,
            data,
            borderColor: '#198754',
            backgroundColor: '#1aa36487',
          },
        ],
      };

    return (
        <div 
          className={`chart-container ${className}`}>
            <Line
                options={options}
                data={chartData}
            />
        </div>
    )
}

export default LineCharts;

// te-demo/src/components/common/LineChart.vue
<script setup lang="ts">
import {
  CategoryScale,
  Chart as ChartJS,
  Filler,
  Legend,
  LinearScale,
  LineElement,
  PointElement,
  Title,
  Tooltip,
} from "chart.js";
import { Line } from "vue-chartjs";

ChartJS.register(
  Title,
  Tooltip,
  Legend,
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement,
  Filler,
);
defineProps<{
  chartData: { labels: string[]; datasets: any[] };
  reRenderKey?: number;
  chartOptions: {
    responsive: boolean;
    plugins: {
      legend?: { display?: boolean };
      tooltip?: { enabled?: boolean };
    };
    interaction?: { intersect?: boolean };
    scales: {
      x: { title: { display: boolean; text: string } };
      y: { title: { display: boolean; text: string } };
    };
  };
}>();
</script>

<template>
  <Line :key="reRenderKey" :options="chartOptions" :data="chartData" />
</template>
